version: "3.7"

services:
  django:
    container_name: hello_django_dev
    restart: "no"
    env_file:
      - ./django/development.env

  graphhopper:
    container_name: graphhopper_dev
    restart: "no"
    env_file:
      - ./django/development.env

  nginx:
    container_name: hello_django_nginx_dev
    restart: "on-failure"

  certbot:
    container_name: hello_django_certbot_dev
    environment:
      DEV: "true"
      NGINX_CONTAINER: "shnake_nginx_dev"
    restart: "no"
